--- #YAML:1.0
name:               Bio-Regexp
version:            0.101
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    common::sense:       0
    Data::Alias:         0
    List::MoreUtils:     0
    Regexp::Exhaustive:  0
    Regexp::Grammars:    0
resources:
    bugtracker:  https://github.com/hoytech/Bio-Regexp/issues
    repository:  git://github.com/hoytech/Bio-Regexp.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
